// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eShopSolution.Data.EF;

#nullable disable

namespace eShopSolution.Data.Migrations
{
    [DbContext(typeof(EShopDbContext))]
    partial class EShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eShopSolution.Data.Entities.BanAn", b =>
                {
                    b.Property<string>("SOBAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SOGHE")
                        .HasColumnType("int");

                    b.HasKey("SOBAN");

                    b.ToTable("BANAN", (string)null);

                    b.HasData(
                        new
                        {
                            SOBAN = "1",
                            SOGHE = 10
                        },
                        new
                        {
                            SOBAN = "2",
                            SOGHE = 5
                        },
                        new
                        {
                            SOBAN = "3",
                            SOGHE = 3
                        },
                        new
                        {
                            SOBAN = "4",
                            SOGHE = 4
                        },
                        new
                        {
                            SOBAN = "5",
                            SOGHE = 6
                        },
                        new
                        {
                            SOBAN = "6",
                            SOGHE = 7
                        },
                        new
                        {
                            SOBAN = "7",
                            SOGHE = 9
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.BoPhan", b =>
                {
                    b.Property<string>("MABOPHAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CHUCNANG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENBOPHAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MABOPHAN");

                    b.ToTable("BOPHAN", (string)null);

                    b.HasData(
                        new
                        {
                            MABOPHAN = "BP1",
                            CHUCNANG = "Quan Li",
                            TENBOPHAN = "QuanLi"
                        },
                        new
                        {
                            MABOPHAN = "BP2",
                            CHUCNANG = "Bep",
                            TENBOPHAN = "Bep"
                        },
                        new
                        {
                            MABOPHAN = "BP3",
                            CHUCNANG = "Phuc Vu",
                            TENBOPHAN = "Phuc Vu"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.CaLamViec", b =>
                {
                    b.Property<string>("MACA")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("GioBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GioKetThuc")
                        .HasColumnType("datetime2");

                    b.HasKey("MACA");

                    b.ToTable("CaLamViec", (string)null);

                    b.HasData(
                        new
                        {
                            MACA = "C1",
                            GioBatDau = new DateTime(2023, 3, 22, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            GioKetThuc = new DateTime(2023, 3, 22, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MACA = "C2",
                            GioBatDau = new DateTime(2023, 3, 22, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            GioKetThuc = new DateTime(2023, 3, 22, 22, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.ChiTietMA", b =>
                {
                    b.Property<string>("MAMONAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MANGUYENLIEU")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MAMONAN", "MANGUYENLIEU");

                    b.HasIndex("MANGUYENLIEU");

                    b.ToTable("ChiTietMonAn", (string)null);

                    b.HasData(
                        new
                        {
                            MAMONAN = "Q01",
                            MANGUYENLIEU = "MNL1"
                        },
                        new
                        {
                            MAMONAN = "Q02",
                            MANGUYENLIEU = "MNL2"
                        },
                        new
                        {
                            MAMONAN = "Q03",
                            MANGUYENLIEU = "MNL3"
                        },
                        new
                        {
                            MAMONAN = "Q04",
                            MANGUYENLIEU = "MNL4"
                        },
                        new
                        {
                            MAMONAN = "Q05",
                            MANGUYENLIEU = "MNL5"
                        },
                        new
                        {
                            MAMONAN = "Q06",
                            MANGUYENLIEU = "MNL6"
                        },
                        new
                        {
                            MAMONAN = "Q07",
                            MANGUYENLIEU = "MNL7"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Khach", b =>
                {
                    b.Property<string>("MAKH")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DIACHIKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MAKH");

                    b.ToTable("Khach", (string)null);

                    b.HasData(
                        new
                        {
                            MAKH = "N111",
                            DIACHIKH = " Hà Nội ",
                            SDTKH = "0987654321",
                            TENKH = " Lê Hiệp "
                        },
                        new
                        {
                            MAKH = "N112",
                            DIACHIKH = " Hà Nội ",
                            SDTKH = "0984822124",
                            TENKH = " Nguyễn Hoàng "
                        },
                        new
                        {
                            MAKH = "N113",
                            DIACHIKH = " Thanh Hóa ",
                            SDTKH = "093422112",
                            TENKH = " Eo Vì "
                        },
                        new
                        {
                            MAKH = "N114",
                            DIACHIKH = " Sài Gòn ",
                            SDTKH = "0984322221",
                            TENKH = " Tuấn Đỗ  "
                        },
                        new
                        {
                            MAKH = "N115",
                            DIACHIKH = " Hà Nội ",
                            SDTKH = "0987654323",
                            TENKH = " Hiixu "
                        },
                        new
                        {
                            MAKH = "N116",
                            DIACHIKH = " Đà Nẵng ",
                            SDTKH = "0987632121",
                            TENKH = " Nợi Tạ "
                        },
                        new
                        {
                            MAKH = "N117",
                            DIACHIKH = " Hà Tĩnh ",
                            SDTKH = "0989832258",
                            TENKH = " Kie Nguyen "
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Kho", b =>
                {
                    b.Property<string>("MAKHO")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Soluong")
                        .HasColumnType("int");

                    b.HasKey("MAKHO");

                    b.ToTable("KHO", (string)null);

                    b.HasData(
                        new
                        {
                            MAKHO = "1",
                            Soluong = 20
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.KhuyenMai", b =>
                {
                    b.Property<string>("MAKM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TENKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MAKM");

                    b.ToTable("KhuyenMai", (string)null);

                    b.HasData(
                        new
                        {
                            MAKM = "KM1",
                            TENKM = "KMNL"
                        },
                        new
                        {
                            MAKM = "KM2",
                            TENKM = "KMNL"
                        },
                        new
                        {
                            MAKM = "KM3",
                            TENKM = "KMNL"
                        },
                        new
                        {
                            MAKM = "KM4",
                            TENKM = "KMNL"
                        },
                        new
                        {
                            MAKM = "KM5",
                            TENKM = "KMNL"
                        },
                        new
                        {
                            MAKM = "KM6",
                            TENKM = "KMNL"
                        },
                        new
                        {
                            MAKM = "KM7",
                            TENKM = "KMNL"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Loaimon", b =>
                {
                    b.Property<string>("MALOAI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MOTA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENLOAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MALOAI");

                    b.ToTable("LoaiMon", (string)null);

                    b.HasData(
                        new
                        {
                            MALOAI = "L1",
                            MOTA = "0",
                            TENLOAI = "Special"
                        },
                        new
                        {
                            MALOAI = "L2",
                            MOTA = "0",
                            TENLOAI = "Special"
                        },
                        new
                        {
                            MALOAI = "L3",
                            MOTA = "0",
                            TENLOAI = "Gia Cầm"
                        },
                        new
                        {
                            MALOAI = "L4",
                            MOTA = "0",
                            TENLOAI = "Thủy Sản"
                        },
                        new
                        {
                            MALOAI = "L5",
                            MOTA = "0",
                            TENLOAI = "Thủy Sản"
                        },
                        new
                        {
                            MALOAI = "L6",
                            MOTA = "0",
                            TENLOAI = "Hải Sản"
                        },
                        new
                        {
                            MALOAI = "L7",
                            MOTA = "0",
                            TENLOAI = "Thủy Sản"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.MonAnKM", b =>
                {
                    b.Property<string>("MAKM")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MAMONAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("GIATRIKM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NDKM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NGAYBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NGAYKT")
                        .HasColumnType("datetime2");

                    b.HasKey("MAKM", "MAMONAN");

                    b.HasIndex("MAMONAN");

                    b.ToTable("MON_AN_KM", (string)null);

                    b.HasData(
                        new
                        {
                            MAKM = "KM1",
                            MAMONAN = "Q07",
                            GIATRIKM = 20000m,
                            NDKM = "THICH",
                            NGAYBD = new DateTime(2022, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NGAYKT = new DateTime(2012, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MAKM = "KM2",
                            MAMONAN = "Q01",
                            GIATRIKM = 20000m,
                            NDKM = "THICH",
                            NGAYBD = new DateTime(2022, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NGAYKT = new DateTime(2012, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MAKM = "KM3",
                            MAMONAN = "Q02",
                            GIATRIKM = 30000m,
                            NDKM = "THICH",
                            NGAYBD = new DateTime(2022, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NGAYKT = new DateTime(2012, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MAKM = "KM4",
                            MAMONAN = "Q03",
                            GIATRIKM = 40000m,
                            NDKM = "THICH",
                            NGAYBD = new DateTime(2022, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NGAYKT = new DateTime(2012, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MAKM = "KM5",
                            MAMONAN = "Q04",
                            GIATRIKM = 50000m,
                            NDKM = "THICH",
                            NGAYBD = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NGAYKT = new DateTime(2012, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MAKM = "KM6",
                            MAMONAN = "Q05",
                            GIATRIKM = 60000m,
                            NDKM = "THICH",
                            NGAYBD = new DateTime(2022, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NGAYKT = new DateTime(2012, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            MAKM = "KM7",
                            MAMONAN = "Q06",
                            GIATRIKM = 70000m,
                            NDKM = "THICH",
                            NGAYBD = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NGAYKT = new DateTime(2012, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NVCa", b =>
                {
                    b.Property<string>("MANV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MACA")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MANV", "MACA");

                    b.HasIndex("MACA");

                    b.ToTable("NV_CA", (string)null);

                    b.HasData(
                        new
                        {
                            MANV = "V01",
                            MACA = "C1"
                        },
                        new
                        {
                            MANV = "V02",
                            MACA = "C1"
                        },
                        new
                        {
                            MANV = "V03",
                            MACA = "C2"
                        },
                        new
                        {
                            MANV = "V04",
                            MACA = "C1"
                        },
                        new
                        {
                            MANV = "V05",
                            MACA = "C1"
                        },
                        new
                        {
                            MANV = "V06",
                            MACA = "C2"
                        },
                        new
                        {
                            MANV = "V07",
                            MACA = "C2"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NguyenLieu", b =>
                {
                    b.Property<string>("MANGUYENLIEU")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DONVITINH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAKHO")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TENNGUYENLIEU")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MANGUYENLIEU");

                    b.HasIndex("MAKHO");

                    b.ToTable("NGUYENLIEU", (string)null);

                    b.HasData(
                        new
                        {
                            MANGUYENLIEU = "MNL1",
                            DONVITINH = "Phần",
                            MAKHO = "1",
                            TENNGUYENLIEU = "Phở"
                        },
                        new
                        {
                            MANGUYENLIEU = "MNL2",
                            DONVITINH = "Phần",
                            MAKHO = "1",
                            TENNGUYENLIEU = "Phở"
                        },
                        new
                        {
                            MANGUYENLIEU = "MNL3",
                            DONVITINH = "Đĩa",
                            MAKHO = "1",
                            TENNGUYENLIEU = "Gà"
                        },
                        new
                        {
                            MANGUYENLIEU = "MNL4",
                            DONVITINH = "Con",
                            MAKHO = "1",
                            TENNGUYENLIEU = "Ba Ba"
                        },
                        new
                        {
                            MANGUYENLIEU = "MNL5",
                            DONVITINH = "Bát",
                            MAKHO = "1",
                            TENNGUYENLIEU = "Ếch"
                        },
                        new
                        {
                            MANGUYENLIEU = "MNL6",
                            DONVITINH = "Con",
                            MAKHO = "1",
                            TENNGUYENLIEU = "Tôm"
                        },
                        new
                        {
                            MANGUYENLIEU = "MNL7",
                            DONVITINH = "Kg",
                            MAKHO = "1",
                            TENNGUYENLIEU = "Cá"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NhaCungCap", b =>
                {
                    b.Property<string>("MANCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DIACHINCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SDTNCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENCC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MANCC");

                    b.ToTable("NHACUNGCAP", (string)null);

                    b.HasData(
                        new
                        {
                            MANCC = "NC1",
                            DIACHINCC = "HN",
                            SDTNCC = "0923182341",
                            TENCC = "Nha"
                        },
                        new
                        {
                            MANCC = "NC2",
                            DIACHINCC = "HN",
                            SDTNCC = "0923322341",
                            TENCC = "Cung"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NhanVien", b =>
                {
                    b.Property<string>("MANV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DIACHINV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GIOITINH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HOTENNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MABOPHAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NGAYSINH")
                        .HasColumnType("datetime2");

                    b.Property<string>("SDTNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MANV");

                    b.HasIndex("MABOPHAN");

                    b.ToTable("NhanVien", (string)null);

                    b.HasData(
                        new
                        {
                            MANV = "V01",
                            DIACHINV = "HN",
                            GIOITINH = "Nu",
                            HOTENNV = "Nguyen Van A",
                            MABOPHAN = "BP1",
                            NGAYSINH = new DateTime(2000, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDTNV = " 09284124100"
                        },
                        new
                        {
                            MANV = "V02",
                            DIACHINV = "HN",
                            GIOITINH = "Nam",
                            HOTENNV = "Nguyen Van B",
                            MABOPHAN = "BP3",
                            NGAYSINH = new DateTime(2000, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDTNV = " 09284121230"
                        },
                        new
                        {
                            MANV = "V03",
                            DIACHINV = "HN",
                            GIOITINH = "Nu",
                            HOTENNV = "Nguyen Van C",
                            MABOPHAN = "BP2",
                            NGAYSINH = new DateTime(2000, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDTNV = " 09284124532"
                        },
                        new
                        {
                            MANV = "V04",
                            DIACHINV = "HN",
                            GIOITINH = "Nam",
                            HOTENNV = "Nguyen Van D",
                            MABOPHAN = "BP2",
                            NGAYSINH = new DateTime(2000, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDTNV = " 09284124234"
                        },
                        new
                        {
                            MANV = "V05",
                            DIACHINV = "HN",
                            GIOITINH = "Nu",
                            HOTENNV = "Nguyen Van E",
                            MABOPHAN = "BP3",
                            NGAYSINH = new DateTime(2000, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDTNV = " 09284124100"
                        },
                        new
                        {
                            MANV = "V06",
                            DIACHINV = "HN",
                            GIOITINH = "Nu",
                            HOTENNV = "Nguyen Van G",
                            MABOPHAN = "BP3",
                            NGAYSINH = new DateTime(2000, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDTNV = " 09284124123"
                        },
                        new
                        {
                            MANV = "V07",
                            DIACHINV = "HN",
                            GIOITINH = "Nam",
                            HOTENNV = "Nguyen Van H",
                            MABOPHAN = "BP2",
                            NGAYSINH = new DateTime(2000, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SDTNV = " 09234124100"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.PhieuCC", b =>
                {
                    b.Property<string>("MANCC")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MANGUYENLIEU")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MANCC", "MANGUYENLIEU");

                    b.HasIndex("MANGUYENLIEU");

                    b.ToTable("Phieu_CC", (string)null);

                    b.HasData(
                        new
                        {
                            MANCC = "NC1",
                            MANGUYENLIEU = "MNL1"
                        },
                        new
                        {
                            MANCC = "NC2",
                            MANGUYENLIEU = "MNL2"
                        },
                        new
                        {
                            MANCC = "NC1",
                            MANGUYENLIEU = "MNL3"
                        },
                        new
                        {
                            MANCC = "NC2",
                            MANGUYENLIEU = "MNL4"
                        },
                        new
                        {
                            MANCC = "NC1",
                            MANGUYENLIEU = "MNL5"
                        },
                        new
                        {
                            MANCC = "NC2",
                            MANGUYENLIEU = "MNL6"
                        },
                        new
                        {
                            MANCC = "NC1",
                            MANGUYENLIEU = "MNL7"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.PhieuDat", b =>
                {
                    b.Property<string>("SOPHIEUDAT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MAKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NGAYGIODAT")
                        .HasColumnType("datetime2");

                    b.Property<string>("SOBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SOLUONGBAN")
                        .HasColumnType("int");

                    b.HasKey("SOPHIEUDAT");

                    b.HasIndex("MAKH");

                    b.HasIndex("SOBAN");

                    b.ToTable("PHIEUDAT", (string)null);

                    b.HasData(
                        new
                        {
                            SOPHIEUDAT = "N01",
                            MAKH = "N111",
                            NGAYGIODAT = new DateTime(1991, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOBAN = "1",
                            SOLUONGBAN = 20
                        },
                        new
                        {
                            SOPHIEUDAT = "N02",
                            MAKH = "N112",
                            NGAYGIODAT = new DateTime(1991, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOBAN = "2",
                            SOLUONGBAN = 10
                        },
                        new
                        {
                            SOPHIEUDAT = "N03",
                            MAKH = "N113",
                            NGAYGIODAT = new DateTime(1992, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOBAN = "3",
                            SOLUONGBAN = 45
                        },
                        new
                        {
                            SOPHIEUDAT = "N04",
                            MAKH = "N114",
                            NGAYGIODAT = new DateTime(1989, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOBAN = "4",
                            SOLUONGBAN = 7
                        },
                        new
                        {
                            SOPHIEUDAT = "N05",
                            MAKH = "N115",
                            NGAYGIODAT = new DateTime(1910, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOBAN = "5",
                            SOLUONGBAN = 23
                        },
                        new
                        {
                            SOPHIEUDAT = "N06",
                            MAKH = "N116",
                            NGAYGIODAT = new DateTime(1948, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOBAN = "6",
                            SOLUONGBAN = 30
                        },
                        new
                        {
                            SOPHIEUDAT = "N07",
                            MAKH = "N117",
                            NGAYGIODAT = new DateTime(1920, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOBAN = "7",
                            SOLUONGBAN = 27
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.PhieuGoi", b =>
                {
                    b.Property<string>("SOPHIEUGOI")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MAKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MAMONAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SOPHIEUGOI");

                    b.HasIndex("MAKH");

                    b.HasIndex("MAMONAN");

                    b.ToTable("PHIEU_GOI", (string)null);

                    b.HasData(
                        new
                        {
                            SOPHIEUGOI = "A1",
                            MAKH = "N111",
                            MAMONAN = "Q01"
                        },
                        new
                        {
                            SOPHIEUGOI = "A2",
                            MAKH = "N112",
                            MAMONAN = "Q01"
                        },
                        new
                        {
                            SOPHIEUGOI = "A3",
                            MAKH = "N113",
                            MAMONAN = "Q02"
                        },
                        new
                        {
                            SOPHIEUGOI = "A4",
                            MAKH = "N114",
                            MAMONAN = "Q03"
                        },
                        new
                        {
                            SOPHIEUGOI = "A5",
                            MAKH = "N115",
                            MAMONAN = "Q04"
                        },
                        new
                        {
                            SOPHIEUGOI = "A6",
                            MAKH = "N116",
                            MAMONAN = "Q05"
                        },
                        new
                        {
                            SOPHIEUGOI = "A7",
                            MAKH = "N117",
                            MAMONAN = "Q06"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.PhieuNhap", b =>
                {
                    b.Property<string>("SOPHIEUNHAP")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DonGiaNhap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MANGUYENLIEU")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MANV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoLuongNhap")
                        .HasColumnType("int");

                    b.HasKey("SOPHIEUNHAP");

                    b.HasIndex("MANGUYENLIEU");

                    b.HasIndex("MANV");

                    b.ToTable("PhieuNhap", (string)null);

                    b.HasData(
                        new
                        {
                            SOPHIEUNHAP = "PN1",
                            DonGiaNhap = 10000m,
                            MANGUYENLIEU = "MNL1",
                            MANV = "V01",
                            NgayNhap = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongNhap = 4
                        },
                        new
                        {
                            SOPHIEUNHAP = "PN2",
                            DonGiaNhap = 20000m,
                            MANGUYENLIEU = "MNL1",
                            MANV = "V01",
                            NgayNhap = new DateTime(2023, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongNhap = 4
                        },
                        new
                        {
                            SOPHIEUNHAP = "PN3",
                            DonGiaNhap = 15000m,
                            MANGUYENLIEU = "MNL2",
                            MANV = "V01",
                            NgayNhap = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongNhap = 4
                        },
                        new
                        {
                            SOPHIEUNHAP = "PN4",
                            DonGiaNhap = 12000m,
                            MANGUYENLIEU = "MNL3",
                            MANV = "V02",
                            NgayNhap = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongNhap = 1
                        },
                        new
                        {
                            SOPHIEUNHAP = "PN5",
                            DonGiaNhap = 13000m,
                            MANGUYENLIEU = "MNL4",
                            MANV = "V02",
                            NgayNhap = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SoLuongNhap = 4
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Product", b =>
                {
                    b.Property<string>("MAMONAN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DONGIA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DONVITINh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MALOAI")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MOTA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TENMON")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MAMONAN");

                    b.HasIndex("MALOAI");

                    b.ToTable("MON_AN", (string)null);

                    b.HasData(
                        new
                        {
                            MAMONAN = "Q01",
                            DONGIA = 40000m,
                            DONVITINh = "Phần",
                            MALOAI = "L1",
                            MOTA = "0",
                            TENMON = "Phở Cuốn"
                        },
                        new
                        {
                            MAMONAN = "Q02",
                            DONGIA = 50000m,
                            DONVITINh = "Phần",
                            MALOAI = "L2",
                            MOTA = "0",
                            TENMON = "Phở Trộn"
                        },
                        new
                        {
                            MAMONAN = "Q03",
                            DONGIA = 60000m,
                            DONVITINh = "Đĩa",
                            MALOAI = "L3",
                            MOTA = "0",
                            TENMON = "Thịt Gà Luộc"
                        },
                        new
                        {
                            MAMONAN = "Q04",
                            DONGIA = 70000m,
                            DONVITINh = "Con",
                            MALOAI = "L4",
                            MOTA = "0",
                            TENMON = "Ba Ba om chuối"
                        },
                        new
                        {
                            MAMONAN = "Q05",
                            DONGIA = 80000m,
                            DONVITINh = "Bát",
                            MALOAI = "L5",
                            MOTA = "0",
                            TENMON = "Ếch om chuối đậu"
                        },
                        new
                        {
                            MAMONAN = "Q06",
                            DONGIA = 90000m,
                            DONVITINh = "Con",
                            MALOAI = "L6",
                            MOTA = "0",
                            TENMON = "Tôm giang muối"
                        },
                        new
                        {
                            MAMONAN = "Q07",
                            DONGIA = 100000m,
                            DONVITINh = "Kg",
                            MALOAI = "L7",
                            MOTA = "0",
                            TENMON = "Cá Tầm Hấp xì dầu"
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.ThanhToan", b =>
                {
                    b.Property<string>("SOPHIEUTT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HINHTHUCTT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MANV")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NGAYGIO")
                        .HasColumnType("datetime2");

                    b.Property<string>("SOPHIEUGOI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SOTIEN")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SOPHIEUTT");

                    b.HasIndex("MAKH");

                    b.HasIndex("MANV");

                    b.ToTable("THANH_TOAN", (string)null);

                    b.HasData(
                        new
                        {
                            SOPHIEUTT = "T01",
                            HINHTHUCTT = "Cash",
                            MAKH = "N111",
                            MANV = "V01",
                            NGAYGIO = new DateTime(2022, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOPHIEUGOI = "A1",
                            SOTIEN = 0m
                        },
                        new
                        {
                            SOPHIEUTT = "T02",
                            HINHTHUCTT = "Cash",
                            MAKH = "N112",
                            MANV = "V02",
                            NGAYGIO = new DateTime(2021, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOPHIEUGOI = "A2",
                            SOTIEN = 0m
                        },
                        new
                        {
                            SOPHIEUTT = "T03",
                            HINHTHUCTT = "CK",
                            MAKH = "N113",
                            MANV = "V03",
                            NGAYGIO = new DateTime(2023, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOPHIEUGOI = "A3",
                            SOTIEN = 0m
                        },
                        new
                        {
                            SOPHIEUTT = "T04",
                            HINHTHUCTT = "CK",
                            MAKH = "N114",
                            MANV = "V04",
                            NGAYGIO = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOPHIEUGOI = "A4",
                            SOTIEN = 0m
                        },
                        new
                        {
                            SOPHIEUTT = "T05",
                            HINHTHUCTT = "Cash",
                            MAKH = "N115",
                            MANV = "V05",
                            NGAYGIO = new DateTime(2021, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOPHIEUGOI = "A5",
                            SOTIEN = 0m
                        },
                        new
                        {
                            SOPHIEUTT = "T06",
                            HINHTHUCTT = "CK",
                            MAKH = "N116",
                            MANV = "V06",
                            NGAYGIO = new DateTime(2020, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOPHIEUGOI = "A6",
                            SOTIEN = 0m
                        },
                        new
                        {
                            SOPHIEUTT = "T07",
                            HINHTHUCTT = "Cash",
                            MAKH = "N117",
                            MANV = "V07",
                            NGAYGIO = new DateTime(1998, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SOPHIEUGOI = "A7",
                            SOTIEN = 0m
                        });
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.ChiTietMA", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.Product", "Product")
                        .WithMany("ChiTietMAs")
                        .HasForeignKey("MAMONAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopSolution.Data.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("ChiTietMAs")
                        .HasForeignKey("MANGUYENLIEU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.MonAnKM", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.KhuyenMai", "KhuyenMai")
                        .WithMany("MonAnKMs")
                        .HasForeignKey("MAKM")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopSolution.Data.Entities.Product", "Product")
                        .WithMany("MonAnKMs")
                        .HasForeignKey("MAMONAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhuyenMai");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NVCa", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.CaLamViec", "CaLamViec")
                        .WithMany("NVCas")
                        .HasForeignKey("MACA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("NVCas")
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CaLamViec");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NguyenLieu", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.Kho", "Kho")
                        .WithMany("NguyenLieus")
                        .HasForeignKey("MAKHO")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kho");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NhanVien", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.BoPhan", "BoPhan")
                        .WithMany("nhanViens")
                        .HasForeignKey("MABOPHAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BoPhan");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.PhieuCC", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.NhaCungCap", "NhaCungCap")
                        .WithMany("PhieuCCs")
                        .HasForeignKey("MANCC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopSolution.Data.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("PhieuCCs")
                        .HasForeignKey("MANGUYENLIEU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("NhaCungCap");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.PhieuDat", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.Khach", "Khach")
                        .WithMany("PhieuDats")
                        .HasForeignKey("MAKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopSolution.Data.Entities.BanAn", "BanAn")
                        .WithMany("PhieuDats")
                        .HasForeignKey("SOBAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BanAn");

                    b.Navigation("Khach");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.PhieuGoi", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.Khach", "Khach")
                        .WithMany("phieuGois")
                        .HasForeignKey("MAKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopSolution.Data.Entities.Product", "Product")
                        .WithMany("phieuGois")
                        .HasForeignKey("MAMONAN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khach");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.PhieuNhap", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.NguyenLieu", "NguyenLieu")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MANGUYENLIEU")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("PhieuNhaps")
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguyenLieu");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Product", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.Loaimon", "Loaimon")
                        .WithMany("products")
                        .HasForeignKey("MALOAI")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Loaimon");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.ThanhToan", b =>
                {
                    b.HasOne("eShopSolution.Data.Entities.Khach", "Khach")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MAKH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eShopSolution.Data.Entities.NhanVien", "NhanVien")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MANV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khach");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.BanAn", b =>
                {
                    b.Navigation("PhieuDats");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.BoPhan", b =>
                {
                    b.Navigation("nhanViens");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.CaLamViec", b =>
                {
                    b.Navigation("NVCas");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Khach", b =>
                {
                    b.Navigation("PhieuDats");

                    b.Navigation("ThanhToans");

                    b.Navigation("phieuGois");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Kho", b =>
                {
                    b.Navigation("NguyenLieus");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.KhuyenMai", b =>
                {
                    b.Navigation("MonAnKMs");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Loaimon", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NguyenLieu", b =>
                {
                    b.Navigation("ChiTietMAs");

                    b.Navigation("PhieuCCs");

                    b.Navigation("PhieuNhaps");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NhaCungCap", b =>
                {
                    b.Navigation("PhieuCCs");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.NhanVien", b =>
                {
                    b.Navigation("NVCas");

                    b.Navigation("PhieuNhaps");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("eShopSolution.Data.Entities.Product", b =>
                {
                    b.Navigation("ChiTietMAs");

                    b.Navigation("MonAnKMs");

                    b.Navigation("phieuGois");
                });
#pragma warning restore 612, 618
        }
    }
}
